### ISSUE TITLE
Issue with error on submission of action on TPU with Colab Pro 

### ISSUE THREAD

**Issue by jpcookie** [KoboldAI/KoboldAI-Client#100]
I have received the following error on Generic 6b united expanded

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 2182, in get_message
    actionsubmit(msg['data'], actionmode=msg['actionmode'])
  File "aiserver.py", line 2679, in actionsubmit
    vars.actions_metadata.append({"Selected Text": data, "Alternative Text": []})
AttributeError: 'dict' object has no attribute 'append'

**Comment by henk717** [comment]
United currently has known editor bugs causing this since that branch still contains experimental changes. For now i recommend sticking to the official version until the author of these changes finds a fix.

**Comment by henk717** [comment]
Give it a try again, should be good now.

**Comment by jpcookie** [comment]
That did work! Thanks.
