### ISSUE TITLE
Bug: ColabKobold TPU NeoX 20B does not work 

### ISSUE THREAD

**Issue by bale-go** [KoboldAI/KoboldAI-Client#124]
ColabKobold TPU NeoX 20B does not generate text after connecting to Cloudfare or Localtunnel. I tried both Official and United versions and various settings to no avail.
I tried Fairseq-dense-13B as a control, and it works.

The error message for NeoX 20B is the following:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 2952, in get_message
    actionsubmit(msg['data'], actionmode=msg['actionmode'])
  File "aiserver.py", line 3495, in actionsubmit
    calcsubmit(data) # Run the first action through the generator
  File "aiserver.py", line 3841, in calcsubmit
    subtxt, min, max = calcsubmitbudget(actionlen, winfo, mem, anotetxt, vars.actions, submission=txt)
  File "aiserver.py", line 3731, in calcsubmitbudget
    lnheader = len(tokenizer._koboldai_header)
AttributeError: 'tokenizers.Tokenizer' object has no attribute '_koboldai_header'

**Comment by vfbd** [comment]
This problem should be fixed now.

**Comment by bale-go** [comment]
Thank you. I checked it with Cloudflare and it works like charm.
