### ISSUE TITLE
MemoryError on a 1080ti for 2.7B model

### ISSUE THREAD

**Issue by yudhanjaya** [KoboldAI/KoboldAI-Client#151]
I've been getting an out-of-memory for the 2.7B model. It should technically fit in my system (see nvidia-smi output at end) - I have 11 GB VRAM. Any ideas as to what's happening? 

```
Downloading config.json: 100%|████████████████████████████████████████████████████| 2.20k/2.20k [00:00<00:00, 1.13MB/s]
Looking for GPU support...FOUND!
Initializing Flask... OK!
Initializing transformers, please wait...

If you don't have enough VRAM to run the model on a single GPU
you can split the model between your CPU and your GPU(s), or between
multiple GPUs if you have more than one.
By putting more 'layers' on a GPU or CPU, more computations will be
done on that device and more VRAM or RAM will be required on that device
(roughly proportional to number of layers).
It should be noted that GPUs are orders of magnitude faster than the CPU.
This model has 32 layers.

       DEVICE ID  |  LAYERS  |  DEVICE NAME
->             0  |       0  |  NVIDIA GeForce GTX 1080 Ti
             N/A  |      32  |  (CPU)

How many of the remaining 32 layers would you like to put into device 0?
You can also enter -1 to allocate all remaining layers to this device.

# of layers> 32

Final device configuration:
       DEVICE ID  |  LAYERS  |  DEVICE NAME
               0  |      32  |  NVIDIA GeForce GTX 1080 Ti
             N/A  |       0  |  (CPU)

Downloading tokenizer_config.json: 100%|███████████████████████████████████████████████| 615/615 [00:00<00:00, 615kB/s]
Downloading vocab.json: 100%|████████████████████████████████████████████████████████| 878k/878k [00:03<00:00, 268kB/s]
Downloading merges.txt: 100%|████████████████████████████████████████████████████████| 446k/446k [00:01<00:00, 259kB/s]
Downloading special_tokens_map.json: 100%|██████████████████████████████████████████| 90.0/90.0 [00:00<00:00, 89.8kB/s]
Downloading pytorch_model.bin: 100%|██████████████████████████████████████████████| 5.06G/5.06G [36:00<00:00, 2.52MB/s]

Loading model tensors:  75%|██████████████████████████████████████████▋              | 362/484 [00:06<00:02, 53.28it/s]

Loading model tensors:   0%|                                                                   | 0/484 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 367, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "E:\KoboldAI\torch_lazy_loader.py", line 233, in torch_load
    callback(retval, f=f, map_location=map_location, pickle_module=pickle_module, **pickle_load_args)
  File "aiserver.py", line 1300, in lazy_load_callback
    model_dict[key] = model_dict[key].materialize(f, map_location="cpu")
  File "E:\KoboldAI\torch_lazy_loader.py", line 102, in materialize
    storage = STORAGE_TYPE_MAP[dtype].from_buffer(f.read(nbytes), "little")
  File "B:\python\lib\site-packages\torch\storage.py", line 538, in from_buffer
    untyped_storage = eval(cls.__module__)._UntypedStorage.from_buffer(*args, **kwargs)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 52428800 bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiserver.py", line 1700, in <module>
    model     = AutoModelForCausalLM.from_pretrained(vars.model, revision=vars.revision, cache_dir="cache", **lowmem)
  File "B:\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 446, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "aiserver.py", line 1225, in new_from_pretrained
    return old_from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 2067, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 371, in load_state_dict
    if f.read().startswith("version"):
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 367, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "E:\KoboldAI\torch_lazy_loader.py", line 233, in torch_load
    callback(retval, f=f, map_location=map_location, pickle_module=pickle_module, **pickle_load_args)
  File "aiserver.py", line 1300, in lazy_load_callback
    model_dict[key] = model_dict[key].materialize(f, map_location="cpu")
  File "E:\KoboldAI\torch_lazy_loader.py", line 102, in materialize
    storage = STORAGE_TYPE_MAP[dtype].from_buffer(f.read(nbytes), "little")
  File "B:\python\lib\zipfile.py", line 940, in read
    data = self._read1(n)
  File "B:\python\lib\zipfile.py", line 1010, in _read1
    data = self._read2(n)
  File "B:\python\lib\zipfile.py", line 1040, in _read2
    data = self._fileobj.read(n)
  File "B:\python\lib\zipfile.py", line 764, in read
    data = self._file.read(n)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiserver.py", line 1702, in <module>
    model     = GPTNeoForCausalLM.from_pretrained(vars.model, revision=vars.revision, cache_dir="cache", **lowmem)
  File "aiserver.py", line 1225, in new_from_pretrained
    return old_from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 2067, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 371, in load_state_dict
    if f.read().startswith("version"):
MemoryError
(base) E:\KoboldAI>nvidia-smi
Thu Sep  8 03:00:05 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:09:00.0  On |                  N/A |
|  0%   40C    P8    18W / 250W |   1254MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

**Comment by yudhanjaya** [comment]
Update: my mistake. Clearly a previous run had locked out some memory. Rebooted the machine and it worked just fine. Cheers!
