### ISSUE TITLE
Couldn't load any model

### ISSUE THREAD

**Issue by Minositu** [KoboldAI/KoboldAI-Client#167]
Here is the traceback that shows after loading the model tensors:

Exception in thread Thread-19:
Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 445, in g
    return f(*a, **k)
  File "aiserver.py", line 3875, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "aiserver.py", line 2616, in load_model
    move_model_to_devices(model)
  File "aiserver.py", line 913, in move_model_to_devices
    accelerate.utils.set_module_tensor_to_device(model, key, target_dtype)
  File "B:\python\lib\site-packages\accelerate\utils\modeling.py", line 118, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: bias is on the meta device, we need a `value` to put in on torch.float16.

**Comment by henk717** [comment]
Should be fixed now, give it a spin on the latest version.
