### ISSUE TITLE
Erebus over-Allocates GPU Memory

### ISSUE THREAD

**Issue by coldReactive** [KoboldAI/KoboldAI-Client#192]
```
       DEVICE ID  |  LAYERS  |  DEVICE NAME
               0  |      22  |  NVIDIA GeForce RTX 3060
             N/A  |      11  |  (Disk cache)
             N/A  |      11  |  (CPU)
INIT       | Loading model tensors:  61%|######1   | 406/664 [00:39<00:34,  7.57it/s]Exception in thread Thread-15:
Traceback (most recent call last):
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 399, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\KoboldAI\torch_lazy_loader.py", line 295, in torch_load
    callback(retval, f=f, map_location=map_location, pickle_module=pickle_module, **pickle_load_args)
  File "aiserver.py", line 2429, in lazy_load_callback
    model_dict[key] = model_dict[key].to(device)
RuntimeError: CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 12.00 GiB total capacity; 11.17 GiB already allocated; 0 bytes free; 11.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 403, in load_state_dict
    if f.read().startswith("version"):
  File "B:\python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1866: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiserver.py", line 2604, in load_model
    model     = AutoModelForCausalLM.from_pretrained(vars.model, revision=vars.revision, cache_dir="cache", **lowmem)
  File "B:\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 463, in from_pretrained
    return model_class.from_pretrained(
  File "aiserver.py", line 1822, in new_from_pretrained
    return old_from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 2326, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys, error_msgs = cls._load_pretrained_model(
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 2536, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "B:\python\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'cache\models--KoboldAI--GPT-NeoX-20B-Erebus\snapshots\1a80940a290452af71caf17a8e520955eb338e0f\pytorch_model-00014-of-00023.bin' at 'cache\models--KoboldAI--GPT-NeoX-20B-Erebus\snapshots\1a80940a290452af71caf17a8e520955eb338e0f\pytorch_model-00014-of-00023.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 466, in g
    return f(*a, **k)
  File "aiserver.py", line 3917, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "aiserver.py", line 2607, in load_model
    raise RuntimeError("One of your GPUs ran out of memory when KoboldAI tried to load your model.")
RuntimeError: One of your GPUs ran out of memory when KoboldAI tried to load your model.
```

I manually set the layers to 22 of 44, and that didn't help. Setting it to 44 of 44 layers changes nothing. I have 64 GB of total DDR4 RAM, and 12 GB of total VRAM.

**Comment by henk717** [comment]
Which version of erebus did you use?

**Comment by coldReactive** [comment]
I'm trying to use 20B.

**Comment by henk717** [comment]
That model needs 64GB of VRAM, so the amount of layers you are using is to high. Try low layer counts, otherwise you may need a smaller model.
