### ISSUE TITLE
Erebus 20B - Can't get Meta Device Value due to it being N/A

### ISSUE THREAD

**Issue by coldReactive** [KoboldAI/KoboldAI-Client#193]
```
INIT       | Searching  | GPU support
INIT       | Found      | GPU support
INIT       | Starting   | Transformers
INIT       | Info       | Final device configuration:
       DEVICE ID  |  LAYERS  |  DEVICE NAME
               0  |      11  |  NVIDIA GeForce RTX 3060
             N/A  |      11  |  (Disk cache)
             N/A  |      22  |  (CPU)
INIT       | Loading model tensors: 100%|##########| 664/664 [01:15<00:00,  8.79it/s]
Exception in thread Thread-24:
Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 466, in g
    return f(*a, **k)
  File "aiserver.py", line 3917, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "aiserver.py", line 2654, in load_model
    move_model_to_devices(model)
  File "aiserver.py", line 941, in move_model_to_devices
    accelerate.utils.set_module_tensor_to_device(model, key, target_dtype)
  File "B:\python\lib\site-packages\accelerate\utils\modeling.py", line 118, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: bias is on the meta device, we need a `value` to put in on torch.float16.
```

**Comment by coldReactive** [comment]
Still happening today even after I did an update:

```
Runtime launching in B: drive mode
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
INIT       | Starting   | LUA bridge
INIT       | OK         | LUA bridge
INIT       | Starting   | LUA Scripts
INIT       | OK         | LUA Scripts
INIT       | OK         | Webserver
MESSAGE    | Webserver started! You may now connect with a browser at http://127.0.0.1:5000
INFO       | __main__:do_connect:3541 - Client connected!
INIT       | Searching  | GPU support
INIT       | Found      | GPU support
INIT       | Starting   | Transformers
INIT       | Info       | Final device configuration:
       DEVICE ID  |  LAYERS  |  DEVICE NAME
               0  |      11  |  NVIDIA GeForce RTX 3060
             N/A  |      11  |  (Disk cache)
             N/A  |      22  |  (CPU)
INIT       | Loading model tensors: 100%|##########| 664/664 [01:20<00:00,  8.25it/s]
Exception in thread Thread-13:
Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 466, in g
    return f(*a, **k)
  File "aiserver.py", line 3914, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "aiserver.py", line 2651, in load_model
    move_model_to_devices(model)
  File "aiserver.py", line 941, in move_model_to_devices
    accelerate.utils.set_module_tensor_to_device(model, key, target_dtype)
  File "B:\python\lib\site-packages\accelerate\utils\modeling.py", line 118, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: bias is on the meta device, we need a `value` to put in on torch.float16.
```

**Comment by coldReactive** [comment]
Also, B: Drive doesn't get removed when the command line for the server terminates sometimes.

**Comment by coldReactive** [comment]
Even after reloading into the browser interface (since the model is loaded) the model accepts no inputs whatsoever. Typing into the big textarea then clicking submit does nothing.

**Comment by SkyeBlep** [comment]
Same crash here.  Although the 32GB version of Erebus worked fine for me, it was just the 64GB version that produced this error.
```
koboldai-client/runtime/envs/koboldai/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 127, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: bias is on the meta device, we need a `value` to put in on torch.float16.
```
