### ISSUE TITLE
Unable to load Erebus 20B due to a meta device error

### ISSUE THREAD

**Issue by SmArtKar** [KoboldAI/KoboldAI-Client#206]
```Exception in thread Thread-31:
Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 828, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 466, in g
    return f(*a, **k)
  File "aiserver.py", line 3914, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "aiserver.py", line 2651, in load_model
    move_model_to_devices(model)
  File "aiserver.py", line 941, in move_model_to_devices
    accelerate.utils.set_module_tensor_to_device(model, key, target_dtype)
  File "B:\python\lib\site-packages\accelerate\utils\modeling.py", line 117, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: bias is on the meta device, we need a `value` to put in on torch.float16.```

**Comment by henk717** [comment]
To load that model in full you need 64GB of VRAM, this error is a common error where to much layers are assigned to a device that can not fit them. I recommend choosing a smaller model (Most consumer hardware can only run 2.7B in full).
