### ISSUE TITLE
Error while canceling generation

### ISSUE THREAD

**Issue by RagingFlames** [KoboldAI/KoboldAI-Client#219]
I was letting the AI generate some text, it was at 75% when I canceled it because I didn't like the direction the story was going. When I pushed cancel it froze up, and got this error int he console.

```
  File "C:\Users\Me/.cache\torch\hub\snakers4_silero-models_master\src\silero\silero.py", line 51, in silero_tts
    from omegaconf import OmegaConf

ModuleNotFoundError: No module named 'omegaconf'
INFO       | koboldai_settings:save_story:936 - Saving
Traceback (most recent call last):
  File "B:\python\lib\site-packages\eventlet\hubs\selects.py", line 59, in wait
    listeners.get(fileno, hub.noop).cb(fileno)
  File "B:\python\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "B:\python\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "B:\python\lib\site-packages\eventlet\wsgi.py", line 352, in __init__
    self.finish()
  File "B:\python\lib\site-packages\eventlet\wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "B:\python\lib\socketserver.py", line 811, in finish
    self.wfile.close()
  File "B:\python\lib\socket.py", line 687, in write
    return self._sock.send(b)
  File "B:\python\lib\site-packages\eventlet\greenio\base.py", line 401, in send
    return self._send_loop(self.fd.send, data, flags)
  File "B:\python\lib\site-packages\eventlet\greenio\base.py", line 388, in _send_loop
    return send_method(data, *args)
```

**Comment by henk717** [comment]
This looks related to the generate audio you enabled, since this is an unfinished experimental feature I recommend turning it off.
