### ISSUE TITLE
Error loading pygmalion 2.7b

### ISSUE THREAD

**Issue by Jake36921** [KoboldAI/KoboldAI-Client#222]
It loads on other models like pygmalion 1.3b and shinen 2.7b but it wouldn't load pygmalion 2.7b

using a cpu if it helps

Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 828, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 466, in g
    return f(*a, **k)
  File "aiserver.py", line 3914, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "aiserver.py", line 2260, in load_model
    loadsettings()
  File "aiserver.py", line 1143, in loadsettings
    js   = json.load(file)
  File "B:\python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "B:\python\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "B:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "B:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Jake36921** [comment]
Nvm, deleting the settings of the model fixed it.
