### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Denzeduous** [KoboldAI/KoboldAI-Client#230]
Hello everyone,

I was attempting to install and run KoboldAI for the first time. However, after installing I ran the update and run KoboldAI options, it asked me for the version I wanted (chose KoboldAI Main I believe it was spelled), then gave this error:
```
The system cannot find the file specified.
Runtime launching in B: drive mode
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\\lib\site.py", line 73, in <module>
    import os
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\\lib\os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\\lib\_collections_abc.py", line 12, in <module>
    GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable
```
Then it immediately kicked me to `(base) D:\KoboldAI>`

I have Python 3.9 64-bit. I don't want to have to upgrade if possible, since I am working on a project currently that requires 3.9 specifically, and having multiple versions is a massive headache. Any advice would be greatly appreciated, thank you!

**Comment by Denzeduous** [comment]
I don't see how that PR is in any way related to this issue, maybe a mistyped reference?
