### ISSUE TITLE
Kolab TPU: grpc_tpu_driver Failed to open the gRPC driver: 4: Deadline Exceeded: absl:No GPU/TPU found

### ISSUE THREAD

**Issue by randomhdl** [KoboldAI/KoboldAI-Client#232]
Not sure if this is the right place to raise it, please close this issue if not.
Surely it could also be some third party library issue but I tried to follow the notebook and its contents are pulled from so many places, scattered over the Internet, it's not a very easy thing for me.

I am trying to use exactly the same notebook I played with since a couple of months, https://colab.research.google.com/github/KoboldAI/KoboldAI-Client/blob/main/colab/TPU.ipynb

Since yesterday at least it can't connect to the TPU allocated.

I tried various variations of the settings but they all look the same.
I have even cleared everything from my Google Drive making sure I start afresh.

**How often does it happen**? Always, at least since yesterday.
**When did it work last time**? About a week ago.
**How to reproduce**?
- navigate to the [TPU KoboldAI Notebook](https://colab.research.google.com/github/KoboldAI/KoboldAI-Client/blob/main/colab/TPU.ipynb)
- select any `Model` you like (my last attempt was with `Nerys 13B V2` but I tried a few, they all fail in the same way)
- keep the version `Official` (but `United` fails in the exactly the same way in the same place)
- leave `Provider` as is, at `Cloudflare` (tried with `Localtunnel` as well, it also failed)
- obviously keep "`use google drive`" checked
- start the cell (click the black "`play`" button to the left of the cell)
- if you don't get TPU allocated, try again in couple of minutes.
- follow the prompts (accept the notebook is not authored by Google and that it can access you Google Drive
- FYI: I tried a GPU version as well, of course with a much smaller model, and it started just fine.

I have deleted `/MyDrive/KoboldAI` folder from my Google Drive for this test, and ran it on the freshly allocated TPU instance so all the steps are executed.

The notebook interrupts the execution after a few minutes with the following error message:

```
Launching KoboldAI with the following options : python3 aiserver.py --model KoboldAI/OPT-13B-Nerys-v2 --colab
[...]
MESSAGE    | Welcome to KoboldAI!
MESSAGE    | You have selected the following Model: KoboldAI/OPT-13B-Nerys-v2
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
Downloading (…)lve/main/config.json: 100%|█████████████████████| 1.51k/1.51k [00:00<00:00, 137kB/s]
Initializing Mesh Transformer JAX, please wait...
Connecting to your Colab instance's TPU
Elapsed Time: 0:00:17  [                                         █             ]
2023-02-11 19:00:05.976424: E external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/grpc_tpu_driver.cc:1070] Failed to open the gRPC driver: 4: Deadline Exceeded: 
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "aiserver.py", line 10214, in <module>
    load_model(initial_load=True)
  File "aiserver.py", line 2806, in load_model
    tpu_mtj_backend.load_model(vars.custmodpth, hf_checkpoint=vars.model not in ("TPUMeshTransformerGPTJ", "TPUMeshTransformerGPTNeoX") and vars.use_colab_tpu, **vars.modelconfig)
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 1194, in load_model
    devices = np.array(jax.devices()[:cores_per_replica]).reshape(mesh_shape)
[...]
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 248, in _get_backend_uncached
    raise RuntimeError(f"Requested backend {platform}, but it failed "
RuntimeError: Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED: Failed to connect to remote server at address: grpc://10.122.148.194:8470. Error from gRPC: Deadline Exceeded. Details: [no further details were provided in the error message in any of the runs]

```

If you are the right audience I would be grateful for taking a look. I thought I'd ask here because it's referenced in the Kolab notebook and the scripts fetched by it.
If you are not, please kindly close it and ideally redirect me to the correct place if possible. Thanks very much in advance.

Kind regards,
just an explorer of the most ridiculous worlds :)

---
Please see the complete run of the Notebook below. There's nothing else there.
```Found TPU at: grpc://10.122.148.194:8470
Now we will need your Google Drive to store settings and saves, you must login with the same account you used for Colab.
Mounted at /content/drive/
--2023-02-11 18:56:44--  https://koboldai.org/ckds
Resolving koboldai.org (koboldai.org)... 104.21.21.176, 172.67.199.170, 2606:4700:3034::6815:15b0, ...
Connecting to koboldai.org (koboldai.org)|104.21.21.176|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://raw.githubusercontent.com/henk717/KoboldAI/united/colabkobold.sh [following]
--2023-02-11 18:56:44--  https://raw.githubusercontent.com/henk717/KoboldAI/united/colabkobold.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6675 (6.5K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]   6.52K  --.-KB/s    in 0s      

2023-02-11 18:56:44 (71.6 MB/s) - written to stdout [6675/6675]

Initialized empty Git repository in /content/KoboldAI-Client/.git/
fatal: No such remote: 'origin'
Fetching origin
remote: Enumerating objects: 6479, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 6479 (delta 40), reused 64 (delta 26), pack-reused 6394
Receiving objects: 100% (6479/6479), 13.72 MiB | 15.16 MiB/s, done.
Resolving deltas: 100% (4086/4086), done.
From https://github.com/koboldai/KoboldAI-Client
 * [new branch]      main       -> origin/main
 * [new tag]         1.18.2     -> 1.18.2
 * [new tag]         1.19.0     -> 1.19.0
 * [new tag]         1.19.1     -> 1.19.1
 * [new tag]         1.19.2     -> 1.19.2
Branch 'main' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'main'
HEAD is now at cc01ad7 Don't install safetensors for MTJ
cp: cannot stat 'softprompts/*': No such file or directory
cp: cannot stat 'presets/*': No such file or directory
cp: cannot stat 'themes/*': No such file or directory
rm: cannot remove 'stories': Is a directory
rm: cannot remove 'userscripts': Is a directory
rm: cannot remove 'softprompts': No such file or directory
rm: cannot remove 'models': Is a directory
rm: cannot remove 'presets': No such file or directory
rm: cannot remove 'themes': No such file or directory
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/VE-FORBRYDERNE/mesh-transformer-jax@ck (from -r requirements_mtj.txt (line 11))
  Cloning https://github.com/VE-FORBRYDERNE/mesh-transformer-jax (to revision ck) to /tmp/pip-req-build-9zup_fws
  Running command git clone --filter=blob:none --quiet https://github.com/VE-FORBRYDERNE/mesh-transformer-jax /tmp/pip-req-build-9zup_fws
  Running command git checkout -b ck --track origin/ck
  Switched to a new branch 'ck'
  Branch 'ck' set up to track remote branch 'ck' from 'origin'.
  Resolved https://github.com/VE-FORBRYDERNE/mesh-transformer-jax to commit 89577e3d49aef94179a138260f6fbd6ca2964327
  Preparing metadata (setup.py) ... done
Collecting torch<1.13,>=1.9
  Downloading torch-1.12.1-cp38-cp38-manylinux1_x86_64.whl (776.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.3/776.3 MB 1.7 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from -r requirements_mtj.txt (line 2)) (1.21.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from -r requirements_mtj.txt (line 3)) (4.64.1)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from -r requirements_mtj.txt (line 4)) (2.25.1)
Collecting dm-haiku==0.0.5
  Downloading dm_haiku-0.0.5-py3-none-any.whl (287 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.3/287.3 KB 22.2 MB/s eta 0:00:00
Collecting jax==0.2.21
  Downloading jax-0.2.21.tar.gz (756 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.7/756.7 KB 44.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting jaxlib<=0.3.7,>=0.1.69
  Downloading jaxlib-0.3.7-cp38-none-manylinux2014_x86_64.whl (68.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.5/68.5 MB 12.6 MB/s eta 0:00:00
Collecting transformers==4.24.0
  Downloading transformers-4.24.0-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 81.2 MB/s eta 0:00:00
Collecting huggingface_hub>=0.10.1
  Downloading huggingface_hub-0.12.0-py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 17.7 MB/s eta 0:00:00
Requirement already satisfied: progressbar2 in /usr/local/lib/python3.8/dist-packages (from -r requirements_mtj.txt (line 10)) (3.38.0)
Requirement already satisfied: flask in /usr/local/lib/python3.8/dist-packages (from -r requirements_mtj.txt (line 12)) (1.1.4)
Collecting Flask-SocketIO
  Downloading Flask_SocketIO-5.3.2-py3-none-any.whl (17 kB)
Collecting flask-cloudflared==0.0.10
  Downloading flask_cloudflared-0.0.10-py3-none-any.whl (5.9 kB)
Collecting flask-ngrok
  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)
Collecting eventlet
  Downloading eventlet-0.33.3-py2.py3-none-any.whl (226 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.8/226.8 KB 22.5 MB/s eta 0:00:00
Collecting dnspython==2.2.1
  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 KB 25.9 MB/s eta 0:00:00
Collecting lupa==1.10
  Downloading lupa-1.10-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (304 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.6/304.6 KB 27.3 MB/s eta 0:00:00
Requirement already satisfied: markdown in /usr/local/lib/python3.8/dist-packages (from -r requirements_mtj.txt (line 19)) (3.4.1)
Collecting bleach==4.1.0
  Downloading bleach-4.1.0-py2.py3-none-any.whl (157 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.9/157.9 KB 16.5 MB/s eta 0:00:00
Collecting flask-session
  Downloading Flask_Session-0.4.0-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: marshmallow>=3.13 in /usr/local/lib/python3.8/dist-packages (from -r requirements_mtj.txt (line 22)) (3.19.0)
Collecting apispec-webframeworks
  Downloading apispec_webframeworks-0.5.2-py2.py3-none-any.whl (12 kB)
Collecting loguru
  Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 KB 6.4 MB/s eta 0:00:00
Collecting jmp>=0.0.2
  Downloading jmp-0.0.4-py3-none-any.whl (18 kB)
Requirement already satisfied: absl-py>=0.7.1 in /usr/local/lib/python3.8/dist-packages (from dm-haiku==0.0.5->-r requirements_mtj.txt (line 5)) (1.4.0)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.8/dist-packages (from dm-haiku==0.0.5->-r requirements_mtj.txt (line 5)) (0.8.10)
Requirement already satisfied: opt_einsum in /usr/local/lib/python3.8/dist-packages (from jax==0.2.21->-r requirements_mtj.txt (line 6)) (3.3.0)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.8/dist-packages (from jax==0.2.21->-r requirements_mtj.txt (line 6)) (1.7.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 8)) (23.0)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 91.9 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 8)) (3.9.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 8)) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.8/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 8)) (2022.6.2)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from bleach==4.1.0->-r requirements_mtj.txt (line 20)) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from bleach==4.1.0->-r requirements_mtj.txt (line 20)) (0.5.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torch<1.13,>=1.9->-r requirements_mtj.txt (line 1)) (4.4.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (1.24.3)
Collecting flatbuffers<3.0,>=1.12
  Downloading flatbuffers-2.0.7-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: python-utils>=2.3.0 in /usr/local/lib/python3.8/dist-packages (from progressbar2->-r requirements_mtj.txt (line 10)) (3.5.0)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.8/dist-packages (from flask->-r requirements_mtj.txt (line 12)) (1.1.0)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.8/dist-packages (from flask->-r requirements_mtj.txt (line 12)) (1.0.1)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.8/dist-packages (from flask->-r requirements_mtj.txt (line 12)) (2.11.3)
Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.8/dist-packages (from flask->-r requirements_mtj.txt (line 12)) (7.1.2)
Collecting python-socketio>=5.0.2
  Downloading python_socketio-5.7.2-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 KB 5.3 MB/s eta 0:00:00
Requirement already satisfied: greenlet>=0.3 in /usr/local/lib/python3.8/dist-packages (from eventlet->-r requirements_mtj.txt (line 16)) (2.0.2)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown->-r requirements_mtj.txt (line 19)) (6.0.0)
Collecting cachelib
  Downloading cachelib-0.10.2-py3-none-any.whl (18 kB)
Collecting apispec[yaml]>=2.0.0
  Downloading apispec-6.0.2-py3-none-any.whl (29 kB)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4->markdown->-r requirements_mtj.txt (line 19)) (3.12.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from Jinja2<3.0,>=2.10.1->flask->-r requirements_mtj.txt (line 12)) (2.0.1)
Collecting bidict>=0.21.0
  Downloading bidict-0.22.1-py3-none-any.whl (35 kB)
Collecting python-engineio>=4.3.0
  Downloading python_engineio-4.3.4-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.9/52.9 KB 5.8 MB/s eta 0:00:00
Building wheels for collected packages: jax, mesh-transformer
  Building wheel for jax (setup.py) ... done
  Created wheel for jax: filename=jax-0.2.21-py3-none-any.whl size=869303 sha256=c4754f9ecce7f54ec6092b62d1568096010aa2ee5e41887ca351311a65ad9b14
  Stored in directory: /root/.cache/pip/wheels/01/7c/ca/72e45492b0198bc701353c992bd445d7cfa1c9ceee450d49e6
  Building wheel for mesh-transformer (setup.py) ... done
  Created wheel for mesh-transformer: filename=mesh_transformer-0.0.0+ck.487.g89577e3-py3-none-any.whl size=32888 sha256=7e8ee7ce81b2d3a855848abbf53b53279c21996bf3727aa10703ee3b9a7a54de
  Stored in directory: /tmp/pip-ephem-wheel-cache-k7by1xfj/wheels/50/09/54/77e0461825b7437e038b90ad231f6a04154a1f5970fdfff931
Successfully built jax mesh-transformer
Installing collected packages: tokenizers, mesh-transformer, lupa, flatbuffers, torch, python-engineio, loguru, jmp, dnspython, cachelib, bleach, bidict, apispec, python-socketio, jaxlib, jax, huggingface_hub, eventlet, dm-haiku, transformers, Flask-SocketIO, flask-session, flask-ngrok, flask-cloudflared, apispec-webframeworks
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 23.1.21
    Uninstalling flatbuffers-23.1.21:
      Successfully uninstalled flatbuffers-23.1.21
  Attempting uninstall: torch
    Found existing installation: torch 1.13.1+cu116
    Uninstalling torch-1.13.1+cu116:
      Successfully uninstalled torch-1.13.1+cu116
  Attempting uninstall: dnspython
    Found existing installation: dnspython 2.3.0
    Uninstalling dnspython-2.3.0:
      Successfully uninstalled dnspython-2.3.0
  Attempting uninstall: bleach
    Found existing installation: bleach 6.0.0
    Uninstalling bleach-6.0.0:
      Successfully uninstalled bleach-6.0.0
  Attempting uninstall: jaxlib
    Found existing installation: jaxlib 0.3.25+cuda11.cudnn805
    Uninstalling jaxlib-0.3.25+cuda11.cudnn805:
      Successfully uninstalled jaxlib-0.3.25+cuda11.cudnn805
  Attempting uninstall: jax
    Found existing installation: jax 0.3.25
    Uninstalling jax-0.3.25:
      Successfully uninstalled jax-0.3.25
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1+cu116 requires torch==1.13.1, but you have torch 1.12.1 which is incompatible.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 1.12.1 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 1.12.1 which is incompatible.
Successfully installed Flask-SocketIO-5.3.2 apispec-6.0.2 apispec-webframeworks-0.5.2 bidict-0.22.1 bleach-4.1.0 cachelib-0.10.2 dm-haiku-0.0.5 dnspython-2.2.1 eventlet-0.33.3 flask-cloudflared-0.0.10 flask-ngrok-0.0.25 flask-session-0.4.0 flatbuffers-2.0.7 huggingface_hub-0.12.0 jax-0.2.21 jaxlib-0.3.7 jmp-0.0.4 loguru-0.6.0 lupa-1.10 mesh-transformer-0.0.0+ck.487.g89577e3 python-engineio-4.3.4 python-socketio-5.7.2 tokenizers-0.13.2 torch-1.12.1 transformers-4.24.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-510
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libaria2-0 libc-ares2
The following NEW packages will be installed:
  aria2 libaria2-0 libc-ares2 netbase
0 upgraded, 4 newly installed, 0 to remove and 21 not upgraded.
Need to get 1,490 kB of archives.
After this operation, 6,002 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 netbase all 6.1 [13.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libc-ares2 amd64 1.15.0-1ubuntu0.1 [38.2 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 libaria2-0 amd64 1.35.0-1build1 [1,082 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/universe amd64 aria2 amd64 1.35.0-1build1 [356 kB]
Fetched 1,490 kB in 1s (1,303 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 4.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package netbase.
(Reading database ... 128048 files and directories currently installed.)
Preparing to unpack .../archives/netbase_6.1_all.deb ...
Unpacking netbase (6.1) ...
Selecting previously unselected package libc-ares2:amd64.
Preparing to unpack .../libc-ares2_1.15.0-1ubuntu0.1_amd64.deb ...
Unpacking libc-ares2:amd64 (1.15.0-1ubuntu0.1) ...
Selecting previously unselected package libaria2-0:amd64.
Preparing to unpack .../libaria2-0_1.35.0-1build1_amd64.deb ...
Unpacking libaria2-0:amd64 (1.35.0-1build1) ...
Selecting previously unselected package aria2.
Preparing to unpack .../aria2_1.35.0-1build1_amd64.deb ...
Unpacking aria2 (1.35.0-1build1) ...
Setting up libc-ares2:amd64 (1.15.0-1ubuntu0.1) ...
Setting up netbase (6.1) ...
Setting up libaria2-0:amd64 (1.35.0-1build1) ...
Setting up aria2 (1.35.0-1build1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
/tools/node/bin/lt -> /tools/node/lib/node_modules/localtunnel/bin/lt.js
+ localtunnel@2.0.2
added 22 packages from 22 contributors in 1.949s
Launching KoboldAI with the following options : python3 aiserver.py --model KoboldAI/OPT-13B-Nerys-v2 --colab
2023-02-11 18:59:05.174591: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-11 18:59:09.438177: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-02-11 18:59:09.443852: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-02-11 18:59:09.443915: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
MESSAGE    | Welcome to KoboldAI!
MESSAGE    | You have selected the following Model: KoboldAI/OPT-13B-Nerys-v2
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
Downloading (…)lve/main/config.json: 100%|█████████████████████| 1.51k/1.51k [00:00<00:00, 137kB/s]
Initializing Mesh Transformer JAX, please wait...
Connecting to your Colab instance's TPU
Elapsed Time: 0:00:17  [                                         █             ]
2023-02-11 19:00:05.976424: E external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/grpc_tpu_driver.cc:1070] Failed to open the gRPC driver: 4: Deadline Exceeded: 
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "aiserver.py", line 10214, in <module>
    load_model(initial_load=True)
  File "aiserver.py", line 2806, in load_model
    tpu_mtj_backend.load_model(vars.custmodpth, hf_checkpoint=vars.model not in ("TPUMeshTransformerGPTJ", "TPUMeshTransformerGPTNeoX") and vars.use_colab_tpu, **vars.modelconfig)
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 1194, in load_model
    devices = np.array(jax.devices()[:cores_per_replica]).reshape(mesh_shape)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 314, in devices
    return get_backend(backend).devices()
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 258, in get_backend
    return _get_backend_uncached(platform)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 248, in _get_backend_uncached
    raise RuntimeError(f"Requested backend {platform}, but it failed "
RuntimeError: Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED: Failed to connect to remote server at address: grpc://10.122.148.194:8470. Error from gRPC: Deadline Exceeded. Details: ```

**Comment by randomhdl** [comment]
I guess this is upstream problem? https://github.com/google/jax/issues/8118

**Comment by henk717** [comment]
Correct, https://github.com/googlecolab/colabtools/issues/3405

**Comment by randomhdl** [comment]
Thank you very much! Closing it now, there's no point in having it here I think.

**Comment by henk717** [comment]
Re-opening so people don't keep creating new issues for this.

**Comment by henk717** [comment]
Google has fixed the issue

**Comment by Devetec** [comment]
No, they have not.

**Comment by henk717** [comment]
They did, but broke it again two weeks later. Possibly permanently since they partially broke it on purpose.

**Comment by SirRizzalot** [comment]
> 

![image](https://user-images.githubusercontent.com/124323253/226117342-c6268f4c-c902-467e-9563-e51b0601a333.png)
@henk717 , would limiting the download to jaxlib to 0.1.69 fix the problem? Or that's what they meant by "we've taken out all the old drivers and don't know how to put it back"

**Comment by arcticlinux** [comment]
@henk717 I've found a way to get it to run on Colab with TPU support, see #307
