### ISSUE TITLE
DEADLINE_EXCEEDED error when running TPU mode on google colab, works find when using gpu mode

### ISSUE THREAD

**Issue by pvnotpv** [KoboldAI/KoboldAI-Client#235]
here's the full error 
---

Downloading (…)lve/main/config.json: 100%|████████████████████| 1.51k/1.51k [00:00<00:00, 86.3kB/s]
Initializing Mesh Transformer JAX, please wait...
Connecting to your Colab instance's TPU
Elapsed Time: 0:00:01  [                  █                                    ]
2023-02-15 17:41:46.158200: E external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/grpc_tpu_driver.cc:1070] Failed to open the gRPC driver: 4: Deadline Exceeded: 
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "aiserver.py", line 10214, in <module>
    load_model(initial_load=True)
  File "aiserver.py", line 2806, in load_model
    tpu_mtj_backend.load_model(vars.custmodpth, hf_checkpoint=vars.model not in ("TPUMeshTransformerGPTJ", "TPUMeshTransformerGPTNeoX") and vars.use_colab_tpu, **vars.modelconfig)
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 1194, in load_model
    devices = np.array(jax.devices()[:cores_per_replica]).reshape(mesh_shape)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 314, in devices
    return get_backend(backend).devices()
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 258, in get_backend
    return _get_backend_uncached(platform)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 248, in _get_backend_uncached
    raise RuntimeError(f"Requested backend {platform}, but it failed "
RuntimeError: Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED: Failed to connect to remote server at address: grpc://10.78.46.10:8470. Error from gRPC: Deadline Exceeded. Details: 

---

the details is not visible.

**Comment by henk717** [comment]
Known issue because Google broke the TPU driver.
Its also been reported on : https://github.com/KoboldAI/KoboldAI-Client/issues/232

I will close this instance of the issue to avoid duplicates, there isn't anything we can do about this and it requires some upstream fixes.
Ideally google notices and fixes : https://github.com/googlecolab/colabtools/issues/3405
