### ISSUE TITLE
TypeError: emit() got an unexpected keyword argument 'broadcast'

### ISSUE THREAD

**Issue by alekratz** [KoboldAI/KoboldAI-Client#264]
Hello, I'm really enjoying KoboldAI. I have been using the Google Colab version primarily. Earlier today, I was able to run the Colab version without a problem. However, as of writing, I get the title error on startup. I've included the stack trace at the bottom under the fold (it is quite long).

# What I have tried

I did some digging on this and it appears that very recently (a few hours ago as of writing this) the python-socketio project (used by the Flask-socketio dependency) had a minor point update from 5.7 -> 5.8. I haven't looked to closely at it, but I believe this is the package where the error is originating. When I run the ipynb, the install dialog indicates that it is installing this very new version of python-socketio:

```
Collecting python-socketio>=5.0.2
  Downloading python_socketio-5.8.0-py3-none-any.whl (56 kB)
```

I believe this is the cause of the error, but I haven't gone on to install an older version and verify yet.

# What I haven't tried

* I haven't looked too closely at the python-socketio project to see what has actually changed, and what I'm saying is true. I'm just going off of error messages and circumstantial evidence.
* I haven't been able to reproduce this locally, I assume python-socketio is cached somewhere with micromamba (outside of the runtime/ directory) and I don't know where that is so I can remove it and try again.
* I haven't tried forking this repository to my own account, adding a `python-socketio<=5.7` constraint to requirements.txt. This is what I plan on trying next later, when I get the chance. When I do this, I'll update this issue with the results.

<details>

```
ERROR      | __main__:do_connect:4137 - An error has been caught in function 'do_connect', process 'MainProcess' (10290), thread 'MainThread' (140021992789824):
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 824, in _handle_event
    ret = handler(auth)
          │       └ None
          └ <function do_connect at 0x7f589936c1f0>

  File "/content/KoboldAI-Client/aiserver.py", line 592, in g
    return f(*a, **k)
           │  │    └ {}
           │  └ (None,)
           └ <function do_connect at 0x7f589936c160>

TypeError: do_connect() takes 0 positional arguments but 1 was given


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
             │         │       └ {}
             │         └ ([('127.0.0.1', 36202), <eventlet.greenio.base.GreenSocket object at 0x7f5898dde040>, 'idle'],)
             └ <bound method Server.process_request of <eventlet.wsgi.Server object at 0x7f5898fdfee0>>

  File "/usr/local/lib/python3.9/dist-packages/eventlet/wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
    │     │        │           └ <eventlet.wsgi.Server object at 0x7f5898fdfee0>
    │     │        └ [('127.0.0.1', 36202), <eventlet.greenio.base.GreenSocket object at 0x7f5898dde040>, 'idle']
    │     └ <function HttpProtocol.__init__ at 0x7f58a2d69940>
    └ <eventlet.wsgi.HttpProtocol object at 0x7f5898dded00>

  File "/usr/local/lib/python3.9/dist-packages/eventlet/wsgi.py", line 350, in __init__
    self.handle()
    │    └ <function HttpProtocol.handle at 0x7f58a2d69a60>
    └ <eventlet.wsgi.HttpProtocol object at 0x7f5898dded00>

  File "/usr/local/lib/python3.9/dist-packages/eventlet/wsgi.py", line 383, in handle
    self.handle_one_request()
    │    └ <function HttpProtocol.handle_one_request at 0x7f58a2d69b80>
    └ <eventlet.wsgi.HttpProtocol object at 0x7f5898dded00>

  File "/usr/local/lib/python3.9/dist-packages/eventlet/wsgi.py", line 459, in handle_one_request
    self.handle_one_response()
    │    └ <function HttpProtocol.handle_one_response at 0x7f58a2d69c10>
    └ <eventlet.wsgi.HttpProtocol object at 0x7f5898dded00>

  File "/usr/local/lib/python3.9/dist-packages/eventlet/wsgi.py", line 569, in handle_one_response
    result = self.application(self.environ, start_response)
             │    │           │    │        └ <function HttpProtocol.handle_one_response.<locals>.start_response at 0x7f588df89b80>
             │    │           │    └ {'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.multithread': Tr...
             │    │           └ <eventlet.wsgi.HttpProtocol object at 0x7f5898dded00>
             │    └ <Flask 'KoboldAI-Client'>
             └ <eventlet.wsgi.HttpProtocol object at 0x7f5898dded00>

  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function HttpProtocol.handle_one_response.<locals>.start_response at 0x7f588df89b80>
           │    │        └ {'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.multithread': Tr...
           │    └ <flask_socketio._SocketIOMiddleware object at 0x7f58a2d9cf10>
           └ <Flask 'KoboldAI-Client'>

  File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
                 │                    │              └ {'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.multithread': Tr...
                 │                    └ <flask_socketio._SocketIOMiddleware object at 0x7f58a2d9cf10>
                 └ <class 'flask_socketio._SocketIOMiddleware'>

  File "/usr/local/lib/python3.9/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
           │    │            │              │        └ <function HttpProtocol.handle_one_response.<locals>.start_response at 0x7f588df89b80>
           │    │            │              └ {'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.multithread': Tr...
           │    │            └ <function Server.handle_request at 0x7f58a33dad30>
           │    └ <socketio.server.Server object at 0x7f58a2d9cc70>
           └ <flask_socketio._SocketIOMiddleware object at 0x7f58a2d9cf10>

  File "/usr/local/lib/python3.9/dist-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
           │    │   │              │        └ <function HttpProtocol.handle_one_response.<locals>.start_response at 0x7f588df89b80>
           │    │   │              └ {'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.multithread': Tr...
           │    │   └ <function Server.handle_request at 0x7f58a3647a60>
           │    └ <engineio.server.Server object at 0x7f58a2d9ceb0>
           └ <socketio.server.Server object at 0x7f58a2d9cc70>

  File "/usr/local/lib/python3.9/dist-packages/engineio/server.py", line 430, in handle_request
    socket.handle_post_request(environ)
    │      │                   └ {'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.multithread': Tr...
    │      └ <function Socket.handle_post_request at 0x7f58a3647280>
    └ <engineio.socket.Socket object at 0x7f5898dde190>

  File "/usr/local/lib/python3.9/dist-packages/engineio/socket.py", line 126, in handle_post_request
    self.receive(pkt)
    │    │       └ <engineio.packet.Packet object at 0x7f5898e5e850>
    │    └ <function Socket.receive at 0x7f58a3647040>
    └ <engineio.socket.Socket object at 0x7f5898dde190>

  File "/usr/local/lib/python3.9/dist-packages/engineio/socket.py", line 59, in receive
    self.server._trigger_event('message', self.sid, pkt.data,
    │    │      │                         │    │    │   └ '0'
    │    │      │                         │    │    └ <engineio.packet.Packet object at 0x7f5898e5e850>
    │    │      │                         │    └ 'A-WC4czPo1C_s6yrAAAC'
    │    │      │                         └ <engineio.socket.Socket object at 0x7f5898dde190>
    │    │      └ <function Server._trigger_event at 0x7f58a3648040>
    │    └ <engineio.server.Server object at 0x7f58a2d9ceb0>
    └ <engineio.socket.Socket object at 0x7f5898dde190>

  File "/usr/local/lib/python3.9/dist-packages/engineio/server.py", line 621, in _trigger_event
    return self.handlers[event](*args)
           │    │        │       └ ('A-WC4czPo1C_s6yrAAAC', '0')
           │    │        └ 'message'
           │    └ {'connect': <bound method Server._handle_eio_connect of <socketio.server.Server object at 0x7f58a2d9cc70>>, 'message': <bound...
           └ <engineio.server.Server object at 0x7f58a2d9ceb0>

  File "/usr/local/lib/python3.9/dist-packages/socketio/server.py", line 791, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
    │    │               │        │   │          │   └ None
    │    │               │        │   │          └ <socketio.packet.Packet object at 0x7f5898e5e730>
    │    │               │        │   └ None
    │    │               │        └ <socketio.packet.Packet object at 0x7f5898e5e730>
    │    │               └ 'A-WC4czPo1C_s6yrAAAC'
    │    └ <function Server._handle_connect at 0x7f58a33e5040>
    └ <socketio.server.Server object at 0x7f58a2d9cc70>

  File "/usr/local/lib/python3.9/dist-packages/socketio/server.py", line 681, in _handle_connect
    success = self._trigger_event(
              │    └ <function Server._trigger_event at 0x7f58a33e5310>
              └ <socketio.server.Server object at 0x7f58a2d9cc70>

  File "/usr/local/lib/python3.9/dist-packages/socketio/server.py", line 758, in _trigger_event
    return self.handlers[namespace][event](*args)
           │    │        │          │       └ ('D3tmljBsEfFbKuXiAAAD', {'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0...
           │    │        │          └ 'connect'
           │    │        └ '/'
           │    └ {'/': {'get_model_info': <function get_model_info at 0x7f58993e2c10>, 'OAI_Key_Update': <function get_oai_models at 0x7f58993...
           └ <socketio.server.Server object at 0x7f58a2d9cc70>

  File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
           │    │             │        │        │          └ 'D3tmljBsEfFbKuXiAAAD'
           │    │             │        │        └ '/'
           │    │             │        └ 'connect'
           │    │             └ <function do_connect at 0x7f589936c1f0>
           │    └ <function SocketIO._handle_event at 0x7f58a2fab9d0>
           └ <flask_socketio.SocketIO object at 0x7f58a2d9cbb0>

  File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler()
          └ <function do_connect at 0x7f589936c1f0>

  File "/content/KoboldAI-Client/aiserver.py", line 592, in g
    return f(*a, **k)
           │  │    └ {}
           │  └ ()
           └ <function do_connect at 0x7f589936c160>

> File "/content/KoboldAI-Client/aiserver.py", line 4137, in do_connect
    ui2_connect()
    └ <function ui2_connect at 0x7f5899371ee0>

  File "/content/KoboldAI-Client/aiserver.py", line 8037, in ui2_connect
    koboldai_vars.send_to_ui()
    │             └ <function koboldai_vars.send_to_ui at 0x7f58a2f51550>
    └ <koboldai_settings.koboldai_vars object at 0x7f58a2d16190>

  File "/content/KoboldAI-Client/koboldai_settings.py", line 192, in send_to_ui
    self._model_settings.send_to_ui()
    │    │               └ <function settings.send_to_ui at 0x7f58a2f51c10>
    │    └ <koboldai_settings.model_settings object at 0x7f58a2d16250>
    └ <koboldai_settings.koboldai_vars object at 0x7f58a2d16190>

  File "/content/KoboldAI-Client/koboldai_settings.py", line 642, in send_to_ui
    process_variable_changes(self._socketio, self.__class__.__name__.replace("_settings", ""), name, value, None)
    │                        │    │          │    │         │                                  │     └ 0
    │                        │    │          │    │         │                                  └ 'simple_randomness'
    │                        │    │          │    │         └ <member '__name__' of 'getset_descriptor' objects>
    │                        │    │          │    └ <attribute '__class__' of 'object' objects>
    │                        │    │          └ <koboldai_settings.model_settings object at 0x7f58a2d16250>
    │                        │    └ <flask_socketio.SocketIO object at 0x7f58a2d9cbb0>
    │                        └ <koboldai_settings.model_settings object at 0x7f58a2d16250>
    └ <function process_variable_changes at 0x7f58a2facee0>

  File "/content/KoboldAI-Client/koboldai_settings.py", line 91, in process_variable_changes
    socketio.emit("var_changed", {"classname": classname, "name": name, "old_value": clean_var_for_emit(old_value), "value": clean_var_for_emit(value), "transmit_time": transmit_time}, include_self=True, broadcast=True, room=room)
    │        │                                 │                  │                  │                  │                    │                  │                        │                                                       └ 'UI_2'
    │        │                                 │                  │                  │                  │                    │                  │                        └ '2023-03-16 23:32:34.129879'
    │        │                                 │                  │                  │                  │                    │                  └ 0
    │        │                                 │                  │                  │                  │                    └ <function clean_var_for_emit at 0x7f58a2face50>
    │        │                                 │                  │                  │                  └ None
    │        │                                 │                  │                  └ <function clean_var_for_emit at 0x7f58a2face50>
    │        │                                 │                  └ 'simple_randomness'
    │        │                                 └ 'model'
    │        └ <function SocketIO.emit at 0x7f58a2fab4c0>
    └ <flask_socketio.SocketIO object at 0x7f58a2d9cbb0>

  File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 462, in emit
    self.server.emit(event, *args, namespace=namespace, to=to,
    │    │      │    │       │               │             └ 'UI_2'
    │    │      │    │       │               └ '/'
    │    │      │    │       └ ({'classname': 'model', 'name': 'simple_randomness', 'old_value': None, 'value': 0, 'transmit_time': '2023-03-16 23:32:34.129...
    │    │      │    └ 'var_changed'
    │    │      └ <function Server.emit at 0x7f58a33da5e0>
    │    └ <socketio.server.Server object at 0x7f58a2d9cc70>
    └ <flask_socketio.SocketIO object at 0x7f58a2d9cbb0>

TypeError: emit() got an unexpected keyword argument 'broadcast'
```

</details>

**Comment by Kadah** [comment]
I'm getting this since 219b824b9b239c1b14b1df553622a465d63f433a which changed python-socketio to 5.7.2.
Somehow updating to 5.8.0 actually resolves the error for me.
