### ISSUE TITLE
Can't run since 1.19.0; `ModuleNotFoundError: No module named 'transformers.generation_logits_process'`

### ISSUE THREAD

**Issue by bbergeron0** [KoboldAI/KoboldAI-Client#274]
Maybe related with #227.

Steps to reproduce:
```sh
git clone https://github.com/KoboldAI/KoboldAI-Client.git
git checkout 1.19.x #(any version after 1.18.2)
./play.sh
```
Error:
```
Traceback (most recent call last):
  File "aiserver.py", line 10213, in <module>
    patch_transformers()
  File "aiserver.py", line 2007, in patch_transformers
    import transformers.generation_logits_process
ModuleNotFoundError: No module named 'transformers.generation_logits_process'
```

System: Gentoo Linux x64, CUDA 12 (GeForce 3060),

**Comment by bbergeron0** [comment]
Understood. I confirm the web UI starts after checking out the main branch.
