### ISSUE TITLE
The link in the collab does not appear

### ISSUE THREAD

**Issue by Myuless** [KoboldAI/KoboldAI-Client#313]
Here's what comes out
Found TPU at: grpc://10.35.80.178:8470
Now we will need your Google Drive to store settings and saves, you must login with the same account you used for Colab.
Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
--2023-04-25 04:33:22--  https://koboldai.org/ckds
Resolving koboldai.org (koboldai.org)... 172.67.199.170, 104.21.21.176, 2606:4700:3034::6815:15b0, ...
Connecting to koboldai.org (koboldai.org)|172.67.199.170|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://raw.githubusercontent.com/henk717/KoboldAI/united/colabkobold.sh [following]
--2023-04-25 04:33:22--  https://raw.githubusercontent.com/henk717/KoboldAI/united/colabkobold.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6675 (6.5K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]   6.52K  --.-KB/s    in 0s      

2023-04-25 04:33:22 (26.9 MB/s) - written to stdout [6675/6675]

mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/’: File exists
mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/stories/’: File exists
mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/models/’: File exists
mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/settings/’: File exists
mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/softprompts/’: File exists
mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/userscripts/’: File exists
mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/presets/’: File exists
mkdir: cannot create directory ‘/content/drive/MyDrive/KoboldAI/themes/’: File exists
mkdir: cannot create directory ‘/content/KoboldAI-Client’: File exists
Reinitialized existing Git repository in /content/KoboldAI-Client/.git/
Fetching origin
From https://github.com/koboldai/KoboldAI-Client
 * [new branch]      main       -> origin/main
Already on 'main'
HEAD is now at c3bf89a Missed a spot
cp: cannot stat 'softprompts/*': No such file or directory
cp: cannot stat 'presets/*': No such file or directory
cp: cannot stat 'themes/*': No such file or directory
rm: cannot remove 'stories': Is a directory
rm: cannot remove 'userscripts': Is a directory
rm: cannot remove 'models': Is a directory
ln: failed to create symbolic link 'settings/settings': File exists
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/VE-FORBRYDERNE/mesh-transformer-jax@ck (from -r requirements_mtj.txt (line 12))
  Cloning https://github.com/VE-FORBRYDERNE/mesh-transformer-jax (to revision ck) to /tmp/pip-req-build-kebrztom
  Running command git clone --filter=blob:none --quiet https://github.com/VE-FORBRYDERNE/mesh-transformer-jax /tmp/pip-req-build-kebrztom
  Running command git checkout -b ck --track origin/ck
  Switched to a new branch 'ck'
  Branch 'ck' set up to track remote branch 'ck' from 'origin'.
  Resolved https://github.com/VE-FORBRYDERNE/mesh-transformer-jax to commit 89577e3d49aef94179a138260f6fbd6ca2964327
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch<1.13,>=1.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 1)) (1.12.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 2)) (1.24.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 3)) (4.65.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 4)) (2.27.1)
Requirement already satisfied: dm-haiku==0.0.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 5)) (0.0.9)
Requirement already satisfied: jax==0.3.25 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 6)) (0.3.25)
Requirement already satisfied: jaxlib==0.3.25 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 7)) (0.3.25)
Requirement already satisfied: chex==0.1.5 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 8)) (0.1.5)
Requirement already satisfied: transformers==4.24.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 9)) (4.24.0)
Requirement already satisfied: huggingface_hub==0.12.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 10)) (0.12.1)
Requirement already satisfied: progressbar2 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 11)) (4.2.0)
Requirement already satisfied: Flask==2.2.3 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 13)) (2.2.3)
Requirement already satisfied: Flask-SocketIO==5.3.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 14)) (5.3.2)
Requirement already satisfied: python-socketio==5.7.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 15)) (5.7.2)
Requirement already satisfied: flask-cloudflared==0.0.10 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 16)) (0.0.10)
Requirement already satisfied: flask-ngrok in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 17)) (0.0.25)
Requirement already satisfied: eventlet==0.33.3 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 18)) (0.33.3)
Requirement already satisfied: dnspython==2.2.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 19)) (2.2.1)
Requirement already satisfied: lupa==1.10 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 20)) (1.10)
Requirement already satisfied: markdown in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 21)) (3.4.3)
Requirement already satisfied: bleach==4.1.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 22)) (4.1.0)
Requirement already satisfied: flask-session==0.4.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 23)) (0.4.0)
Requirement already satisfied: marshmallow>=3.13 in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 24)) (3.19.0)
Requirement already satisfied: apispec-webframeworks in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 25)) (0.5.2)
Requirement already satisfied: loguru in /usr/local/lib/python3.9/dist-packages (from -r requirements_mtj.txt (line 26)) (0.7.0)
Requirement already satisfied: absl-py>=0.7.1 in /usr/local/lib/python3.9/dist-packages (from dm-haiku==0.0.9->-r requirements_mtj.txt (line 5)) (1.4.0)
Requirement already satisfied: jmp>=0.0.2 in /usr/local/lib/python3.9/dist-packages (from dm-haiku==0.0.9->-r requirements_mtj.txt (line 5)) (0.0.4)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.9/dist-packages (from dm-haiku==0.0.9->-r requirements_mtj.txt (line 5)) (0.8.10)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.9/dist-packages (from jax==0.3.25->-r requirements_mtj.txt (line 6)) (1.10.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from jax==0.3.25->-r requirements_mtj.txt (line 6)) (4.5.0)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.9/dist-packages (from jax==0.3.25->-r requirements_mtj.txt (line 6)) (3.3.0)
Requirement already satisfied: toolz>=0.9.0 in /usr/local/lib/python3.9/dist-packages (from chex==0.1.5->-r requirements_mtj.txt (line 8)) (0.12.0)
Requirement already satisfied: dm-tree>=0.1.5 in /usr/local/lib/python3.9/dist-packages (from chex==0.1.5->-r requirements_mtj.txt (line 8)) (0.1.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 9)) (3.11.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 9)) (6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 9)) (23.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.9/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 9)) (0.13.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/dist-packages (from transformers==4.24.0->-r requirements_mtj.txt (line 9)) (2022.10.31)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.9/dist-packages (from Flask==2.2.3->-r requirements_mtj.txt (line 13)) (8.1.3)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.9/dist-packages (from Flask==2.2.3->-r requirements_mtj.txt (line 13)) (2.2.3)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.9/dist-packages (from Flask==2.2.3->-r requirements_mtj.txt (line 13)) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.9/dist-packages (from Flask==2.2.3->-r requirements_mtj.txt (line 13)) (2.1.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in /usr/local/lib/python3.9/dist-packages (from Flask==2.2.3->-r requirements_mtj.txt (line 13)) (6.4.1)
Requirement already satisfied: python-engineio>=4.3.0 in /usr/local/lib/python3.9/dist-packages (from python-socketio==5.7.2->-r requirements_mtj.txt (line 15)) (4.4.1)
Requirement already satisfied: bidict>=0.21.0 in /usr/local/lib/python3.9/dist-packages (from python-socketio==5.7.2->-r requirements_mtj.txt (line 15)) (0.22.1)
Requirement already satisfied: greenlet>=0.3 in /usr/local/lib/python3.9/dist-packages (from eventlet==0.33.3->-r requirements_mtj.txt (line 18)) (2.0.2)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.9/dist-packages (from eventlet==0.33.3->-r requirements_mtj.txt (line 18)) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.9/dist-packages (from bleach==4.1.0->-r requirements_mtj.txt (line 22)) (0.5.1)
Requirement already satisfied: cachelib in /usr/local/lib/python3.9/dist-packages (from flask-session==0.4.0->-r requirements_mtj.txt (line 23)) (0.10.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->-r requirements_mtj.txt (line 4)) (1.26.15)
Requirement already satisfied: python-utils>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from progressbar2->-r requirements_mtj.txt (line 11)) (3.5.2)
Requirement already satisfied: apispec[yaml]>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from apispec-webframeworks->-r requirements_mtj.txt (line 25)) (6.3.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=3.6.0->Flask==2.2.3->-r requirements_mtj.txt (line 13)) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from Jinja2>=3.0->Flask==2.2.3->-r requirements_mtj.txt (line 13)) (2.1.2)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
netbase is already the newest version (6.1).
aria2 is already the newest version (1.35.0-1build1).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
/tools/node/bin/lt -> /tools/node/lib/node_modules/localtunnel/bin/lt.js
+ localtunnel@2.0.2
updated 1 package in 1.147s

   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │      New major version of npm available! 6.14.8 → 9.6.5       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v9.6.5   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

Launching KoboldAI with the following options : python3 aiserver.py --model KoboldAI/GPT-NeoX-20B-Erebus --colab
2023-04-25 04:33:45.195169: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-25 04:33:48.611429: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
MESSAGE    | Welcome to KoboldAI!
MESSAGE    | You have selected the following Model: KoboldAI/GPT-NeoX-20B-Erebus
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
Initializing Mesh Transformer JAX, please wait...
Connecting to your Colab instance's TPU
Elapsed Time: 0:00:12  [              █                                        ]

8 TPU cores will be used to run the model.

Running in NeoX compatibility mode.

This model has   20 566 007 808   parameters.

Loading model tensors: 100%|█████████████████████████████████████| 664/664 [19:16<00:00,  1.74s/it]
INIT       | Starting   | LUA bridge
INIT       | OK         | LUA bridge
INIT       | Starting   | LUA Scripts
Loading Userscript [Location scanner] <kaipreset_location_scanner.lua>
INIT       | OK         | LUA Scripts
Traceback (most recent call last):
  File "/content/KoboldAI-Client/aiserver.py", line 10313, in <module>
    cloudflare = _run_cloudflared(port)
  File "/usr/local/lib/python3.9/dist-packages/flask_cloudflared.py", line 68, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
  File "/usr/local/lib/python3.9/dist-packages/flask_cloudflared.py", line 100, in _download_cloudflared
    update_cloudflared = subprocess.Popen([(cloudflared_path+'/'+command), 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/local/lib/python3.9/dist-packages/eventlet/green/subprocess.py", line 58, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/tmp/cloudflared-linux-amd64'
TPU backend compilation triggered
INFO       | __main__:settingschanged:1125 - Saving settings.

**Comment by henk717** [comment]
Cloudflare broke, for now you can use Localtunnel to bypass the issue.
