### ISSUE TITLE
when i load the model from local, i get an error: KeyError: 'llama'

### ISSUE THREAD

**Issue by akdcelcopr77** [KoboldAI/KoboldAI-Client#315]
Exception in thread Thread-25 (_handle_event_internal):
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\anaconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\socketio\server.py", line 733, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\ProgramData\anaconda3\lib\site-packages\socketio\server.py", line 758, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\ProgramData\anaconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "C:\ProgramData\anaconda3\lib\site-packages\flask_socketio\__init__.py", line 828, in _handle_event
    ret = handler(*args)
  File "D:\Project\KoboldAI\aiserver.py", line 466, in g
    return f(*a, **k)
  File "D:\Project\KoboldAI\aiserver.py", line 3915, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "D:\Project\KoboldAI\aiserver.py", line 2235, in load_model
    model_config = AutoConfig.from_pretrained(vars.custmodpth.replace('/', '_'), revision=args.revision, cache_dir="cache")
  File "C:\ProgramData\anaconda3\lib\site-packages\transformers\models\auto\configuration_auto.py", line 796, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "C:\ProgramData\anaconda3\lib\site-packages\transformers\models\auto\configuration_auto.py", line 503, in __getitem__
    raise KeyError(key)
KeyError: 'llama'

**Comment by henk717** [comment]
Llama models are not supported on this branch until KoboldAI 2.0 is out, I also see you do not make use of the official runtime we have made but instead rely on your own conda. In which case your huggingface transformers is also to old.
I recommend either using our own runtime or addressing your dependency issue, and then using https://github.com/henk717/koboldai as the KoboldAI version since that one is compatible with newer huggingface versions.
