### ISSUE TITLE
Something went wrong with running Kobold

### ISSUE THREAD

**Issue by TheBot28** [KoboldAI/KoboldAI-Client#322]
[2023-05-01 18:20:17,932] ERROR in app: Exception on /api/v1/model [GET]
Traceback (most recent call last):
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask\app.py", line 2189, in wsgi_app
    ctx.push()
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask\ctx.py", line 377, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask_session\sessions.py", line 329, in open_session
    sid = request.cookies.get(app.session_cookie_name)
AttributeError: 'Flask' object has no attribute 'session_cookie_name'
[2023-05-01 18:20:17,935] ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask\app.py", line 2189, in wsgi_app
    ctx.push()
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask\ctx.py", line 377, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask_session\sessions.py", line 329, in open_session
    sid = request.cookies.get(app.session_cookie_name)
AttributeError: 'Flask' object has no attribute 'session_cookie_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask\app.py", line 1508, in finalize_request
    response = self.process_response(response)
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask\app.py", line 2005, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "C:\Tavern-AI\KoboldAI-Client\miniconda3\lib\site-packages\flask_session\sessions.py", line 353, in save_session
    if session.modified:
AttributeError: 'NoneType' object has no attribute 'modified'

**Comment by henk717** [comment]
This is common when people run our offline installer but forget to choose an option. That then doesn't grab newer update definitions allowing it to update to broken versions. Or when they have conda which the updater in the offline installer can not yet handle but our current one can.

Fix is simple run the KoboldAI Updater again and in your case since your using tavern type 2 and hit enter. Should fix it for you, if not repeat that step once more.
