### ISSUE TITLE
dev build

### ISSUE THREAD

**Issue by scavru** [KoboldAI/KoboldAI-Client#327]
Running a stable build everything works, there is 0cc4m it also works stably. When I run update-koboldai.bat in DEV, an error pops up.

`Runtime launching in B: drive mode
Traceback (most recent call last):
  File "aiserver.py", line 30, in <module>
    import attention_bias
  File "D:\KoboldAI\attention_bias.py", line 16, in <module>
    import torch
  File "B:\python\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] Не найдена указанная процедура. Error loading "B:\python\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
(base) D:\KoboldAI>`

full update log
`1. KoboldAI Main (The Official stable version of KoboldAI)
2. KoboldAI United (Development Version, new features but may break at any time)
Enter your desired version or type your own GIT URL:2
Reinitialized existing Git repository in D:/KoboldAI/.git/
Fetching origin
From https://github.com/henk717/koboldai
 * [new branch]      united     -> origin/united
Already on 'united'
HEAD is now at bb206f5 Don't load peft when unused

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

pytorch/win-64                                              Using cache
pytorch/noarch                                              Using cache
nvidia/win-64                                               Using cache
nvidia/noarch                                               Using cache
conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/msys2/win-64                                             No change
pkgs/main/win-64                                              No change
pkgs/r/win-64                                                 No change
pkgs/msys2/noarch                                             No change

Transaction

  Prefix: B:\python

  All requested packages already installed

Transaction starting
Transaction finished

Installing pip packages: flask-cloudflared==0.0.10, flask-ngrok, flask-cors, lupa==1.10, transformers==4.28.0, huggingf0
Collecting git+https://github.com/VE-FORBRYDERNE/mkultra (from -r B:\mambaf68ssyinYFE (line 9))
  Cloning https://github.com/VE-FORBRYDERNE/mkultra to d:\koboldai\miniconda3\pip-req-build-yulg58mn
  Running command git clone --filter=blob:none --quiet https://github.com/VE-FORBRYDERNE/mkultra 'D:\KoboldAI\miniconda'
  Resolved https://github.com/VE-FORBRYDERNE/mkultra to commit ef544de73ec6a1a4bd55e824d0628fa0ef1323ac
  Preparing metadata (setup.py) ... done
Requirement already satisfied: flask-cloudflared==0.0.10 in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:)
Requirement already satisfied: flask-ngrok in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyin)
Requirement already satisfied: flask-cors in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyinY)
Requirement already satisfied: lupa==1.10 in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyinY)
Requirement already satisfied: transformers==4.28.0 in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mamb)
Requirement already satisfied: huggingface_hub==0.12.1 in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\m)
Requirement already satisfied: safetensors==0.3.1 in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf)
Requirement already satisfied: accelerate==0.18.0 in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf)
Requirement already satisfied: flask-session in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssy)
Requirement already satisfied: python-socketio[client] in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\m)
Requirement already satisfied: ansi2html in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyinYF)
Requirement already satisfied: flask_compress in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ss)
Requirement already satisfied: ijson in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyinYFE (l)
Requirement already satisfied: bitsandbytes in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyi)
Requirement already satisfied: ftfy in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyinYFE (li)
Requirement already satisfied: pydub in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyinYFE (l)
Requirement already satisfied: diffusers in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyinYF)
Requirement already satisfied: peft==0.3.0 in d:\koboldai\miniconda3\python\lib\site-packages (from -r B:\mambaf68ssyin)
Requirement already satisfied: requests in d:\koboldai\miniconda3\python\lib\site-packages (from flask-cloudflared==0.0)
Requirement already satisfied: Flask>=0.8 in d:\koboldai\miniconda3\python\lib\site-packages (from flask-cloudflared==0)
Requirement already satisfied: numpy>=1.17 in d:\koboldai\miniconda3\python\lib\site-packages (from transformers==4.28.)
Requirement already satisfied: filelock in d:\koboldai\miniconda3\python\lib\site-packages (from transformers==4.28.0->)
Requirement already satisfied: packaging>=20.0 in d:\koboldai\miniconda3\python\lib\site-packages (from transformers==4)
Requirement already satisfied: pyyaml>=5.1 in d:\koboldai\miniconda3\python\lib\site-packages (from transformers==4.28.)
Requirement already satisfied: regex!=2019.12.17 in d:\koboldai\miniconda3\python\lib\site-packages (from transformers=)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\koboldai\miniconda3\python\lib\site-packages (fr)
Requirement already satisfied: tqdm>=4.27 in d:\koboldai\miniconda3\python\lib\site-packages (from transformers==4.28.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\koboldai\miniconda3\python\lib\site-packages (from hugg)
Requirement already satisfied: torch>=1.4.0 in d:\koboldai\miniconda3\python\lib\site-packages (from accelerate==0.18.0)
Requirement already satisfied: psutil in d:\koboldai\miniconda3\python\lib\site-packages (from accelerate==0.18.0->-r B)
Requirement already satisfied: Six in d:\koboldai\miniconda3\python\lib\site-packages (from flask-cors->-r B:\mambaf68s)
Requirement already satisfied: cachelib in d:\koboldai\miniconda3\python\lib\site-packages (from flask-session->-r B:\m)
Requirement already satisfied: bidict>=0.21.0 in d:\koboldai\miniconda3\python\lib\site-packages (from python-socketio[)
Requirement already satisfied: python-engineio>=4.3.0 in d:\koboldai\miniconda3\python\lib\site-packages (from python-s)
Requirement already satisfied: websocket-client>=0.54.0 in d:\koboldai\miniconda3\python\lib\site-packages (from python)
Requirement already satisfied: brotli in d:\koboldai\miniconda3\python\lib\site-packages (from flask_compress->-r B:\ma)
Requirement already satisfied: wcwidth>=0.2.5 in d:\koboldai\miniconda3\python\lib\site-packages (from ftfy->-r B:\mamb)
Requirement already satisfied: importlib-metadata in d:\koboldai\miniconda3\python\lib\site-packages (from diffusers->-)
Requirement already satisfied: Pillow in d:\koboldai\miniconda3\python\lib\site-packages (from diffusers->-r B:\mambaf6)
Requirement already satisfied: Jinja2>=3.0 in d:\koboldai\miniconda3\python\lib\site-packages (from Flask>=0.8->flask-c)
Requirement already satisfied: itsdangerous>=2.0 in d:\koboldai\miniconda3\python\lib\site-packages (from Flask>=0.8->f)
Requirement already satisfied: click>=8.0 in d:\koboldai\miniconda3\python\lib\site-packages (from Flask>=0.8->flask-cl)
Requirement already satisfied: Werkzeug>=2.2.2 in d:\koboldai\miniconda3\python\lib\site-packages (from Flask>=0.8->fla)
Requirement already satisfied: zipp>=0.5 in d:\koboldai\miniconda3\python\lib\site-packages (from importlib-metadata->d)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in d:\koboldai\miniconda3\python\lib\site-packages (from packag)
Requirement already satisfied: idna<4,>=2.5 in d:\koboldai\miniconda3\python\lib\site-packages (from requests->flask-cl)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\koboldai\miniconda3\python\lib\site-packages (from reques)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\koboldai\miniconda3\python\lib\site-packages (from requests-)
Requirement already satisfied: certifi>=2017.4.17 in d:\koboldai\miniconda3\python\lib\site-packages (from requests->fl)
Requirement already satisfied: sympy in d:\koboldai\miniconda3\python\lib\site-packages (from torch>=1.4.0->accelerate=)
Requirement already satisfied: networkx in d:\koboldai\miniconda3\python\lib\site-packages (from torch>=1.4.0->accelera)
Requirement already satisfied: colorama in d:\koboldai\miniconda3\python\lib\site-packages (from tqdm>=4.27->transforme)
Requirement already satisfied: MarkupSafe>=2.0 in d:\koboldai\miniconda3\python\lib\site-packages (from Jinja2>=3.0->Fl)
Requirement already satisfied: mpmath>=0.19 in d:\koboldai\miniconda3\python\lib\site-packages (from sympy->torch>=1.4.)`

**Comment by henk717** [comment]
This is because conda is failing to update to Pytorch 2.0, you can either run install_requirements.bat in the mode where it deletes the existing runtime or use the offline installer from https://github.com/henk717/KoboldAI/releases

**Comment by scavru** [comment]
Thank you it worked

**Comment by racinmat** [comment]
It didn't work for me. I got this error even after using the offline installer, when I then upgraded to https://github.com/0cc4m/KoboldAI.
