### ISSUE TITLE
aiserver.py is missing???

### ISSUE THREAD

**Issue by rrennn** [KoboldAI/KoboldAI-Client#394]
H:\koboldai>play --remote
Runtime launching in B: drive mode
Traceback (most recent call last):
  File "aiserver.py", line 15, in <module>
    from modeling.inference_model import GenerationMode
  File "H:\koboldai\modeling\inference_model.py", line 10, in <module>
    import torch
  File "B:\python\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "B:\python\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
(base) H:\koboldai>

**Comment by rrennn** [comment]
i just reinstalled it
