### ISSUE TITLE
Problem at remote-play

### ISSUE THREAD

**Issue by Funbarten** [KoboldAI/KoboldAI-Client#427]
Not sure what I'm missing here, saw a similar issue brought up with the ERROR 193 but the code looks different.

C:\Users\ZURG\OneDrive\Desktop\Bold\KoboldAI-Client-main>play --remote
Runtime launching in subfolder mode
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
INIT       | Starting   | LUA bridge
INIT       | OK         | LUA bridge
INIT       | Starting   | LUA Scripts
INIT       | OK         | LUA Scripts
Traceback (most recent call last):
  File "aiserver.py", line 10316, in <module>
    cloudflare = _run_cloudflared(port)
  File "C:\Users\ZURG\OneDrive\Desktop\Bold\KoboldAI-Client-main\miniconda3\lib\site-packages\flask_cloudflared.py", line 68, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
  File "C:\Users\ZURG\OneDrive\Desktop\Bold\KoboldAI-Client-main\miniconda3\lib\site-packages\flask_cloudflared.py", line 100, in _download_cloudflared
    update_cloudflared = subprocess.Popen([(cloudflared_path+'/'+command), 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "C:\Users\ZURG\OneDrive\Desktop\Bold\KoboldAI-Client-main\miniconda3\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ZURG\OneDrive\Desktop\Bold\KoboldAI-Client-main\miniconda3\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
(base) C:\Users\ZURG\OneDrive\Desktop\Bold\KoboldAI-Client-main>

**Comment by henk717** [comment]
The cloudflare download failed. You can check your temp folder for faulty instances of this program.

**Comment by Funbarten** [comment]
I followed the instructions, both just deleting the file and also replacing it with the downloadable copy linked in the other 193 error thread. Output is the same.

**Comment by Funbarten** [comment]
Had better results with the offline installer, thanks anyway.
