### ISSUE TITLE
model type issue

### ISSUE THREAD

**Issue by HaarishIrfan2171** [KoboldAI/KoboldAI-Client#439]
I use the Qwen1.5-0.5B-Chat-AWQ model and i declare the model path as /home/administrator/KoboldAI-Client/models/qwen/Qwen1.5-0.5B-Chat-AWQ in linux server. 

throw the Error like 

Traceback (most recent call last):
  File "aiserver.py", line 10290, in <module>
    load_model(initial_load=True)
  File "aiserver.py", line 2251, in load_model
    model_config = AutoConfig.from_pretrained(vars.custmodpth, revision=args.revision, cache_dir="cache")
  File "/home/administrator/KoboldAI-Client/runtime/envs/koboldai/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 796, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/administrator/KoboldAI-Client/runtime/envs/koboldai/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 503, in __getitem__
    raise KeyError(key)
KeyError: 'qwen2'

how to resolve it

**Comment by pal404error** [comment]
Hey KoboldAI, really like what you are shipping with KoboldAI-Client. We built ModelRank, an independent leaderboard for open models. Free embeddable badges, 5-dimension scoring, zero paid placements. Want KoboldAI-Client ranked and listed? It is a one-line badge in your README (https://rankmodel.github.io). Appreciate you building in the open.
