### ISSUE TITLE
Unable to load AIDCAT Scenarios or Adventures

### ISSUE THREAD

**Issue by FoxyDysphoria** [KoboldAI/KoboldAI-Client#6]
When trying to load scenarios from an unmodified export JSON from AIDCAT, this traceback is issued:
```Traceback (most recent call last):
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\socketio\server.py", line 688, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_socketio\__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_socketio\__init__.py", line 751, in _handle_event
    ret = handler(*args)
  File "C:\Users\foxyd\Documents\My Games\KoboldAI\KoboldAI-Client-main\aiserver.py", line 343, in get_message
    importRequest()
  File "C:\Users\foxyd\Documents\My Games\KoboldAI\KoboldAI-Client-main\aiserver.py", line 1230, in importRequest
    ob["acts"]  = len(story["actions"])
KeyError: 'actions'
```

When trying to load adventures from an unmodified export JSON, this traceback is issued: 
```Traceback (most recent call last):
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\socketio\server.py", line 688, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_socketio\__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_socketio\__init__.py", line 751, in _handle_event
    ret = handler(*args)
  File "C:\Users\foxyd\Documents\My Games\KoboldAI\KoboldAI-Client-main\aiserver.py", line 343, in get_message
    importRequest()
  File "C:\Users\foxyd\Documents\My Games\KoboldAI\KoboldAI-Client-main\aiserver.py", line 1212, in importRequest
    vars.importjs = json.load(file)
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\foxyd\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 144658: character maps to <undefined>
```

I'm not sure how these particular issues could've happened, considering they're just the raw, exported files.  

**EDIT:** Even the included sample story fails to load.

**Comment by KoboldAI** [comment]
Howdy, thanks for the report!
Scenario support hasn't been added yet, so you definitely won't be able to import those.
The Adventures is an issue though. It looks like the json decoder is choking on one of the characters in your export file. Let me do a little digging and see what I can do.

**Comment by FoxyDysphoria** [comment]
> Howdy, thanks for the report!
> Scenario support hasn't been added yet, so you definitely won't be able to import those.
> The Adventures is an issue though. It looks like the json decoder is choking on one of the characters in your export file. Let me do a little digging and see what I can do.

I figured scenarios weren't supported yet, but also figured I might as well give it a try, just to sanity-check myself.

> Edit: Missed your edit. I just tested loading the sample story here without an issue. Are you trying to load it from the Import prompt or the Load prompt?

I was using the import prompt for everything.

**Comment by FoxyDysphoria** [comment]
If you'd like, I can provide you with my exported adventures. I would prefer to do so in private though, so if you'd like, I can send them to you via Discord. My tag on there is Dys#0001

**Comment by KoboldAI** [comment]
Sent you a Friend request,

**Comment by KoboldAI** [comment]
Git updated with the fixes we worked on. Thanks again!
